"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';
import { safeLocalStorage } from '@/utils/storage';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_updates: 'Blogs',
    nav_planning: 'Planning',
    nav_investment: 'Investment',
    nav_contact: 'Contact Us',
    btn_unlock: 'Unlock Now',
    btn_view: 'View Map',
    btn_get_touch: 'Contact Us',
    search_placeholder: 'Search Documents...',
    footer_tagline: 'The independent portal for Dholera Smart City infrastructure, investment, and planning intelligence.',
    footer_quick_links: 'Quick Links',
    footer_contact_info: 'Contact Information',
    footer_owner: 'Owner Details',
    footer_address: 'Address',
    footer_email: 'Email',
    footer_phone: 'Phone',
    pdf_cat_official: 'Verified PDFs',
    pdf_cat_naksha: 'Naksha Maps',
    pdf_cat_dp: 'DP Maps',
    hero_title: 'Dholera Growth Platform',
    hero_subtitle: 'Evidence-backed infrastructure tracking for smart investors.',
    terms_and_conditions: 'Terms and Conditions',
    last_updated: 'Last updated: May 20, 2026',
    support_email: 'support@dholeraplatform.com',
    evidence: 'Evidence',
    certainty: 'Certainty',
    scanning_archives: 'Scanning Archives...',
    the_loop: 'The Loop',
    proof: 'Proof',
    step: 'Step ',
    evidence_signals: 'Evidence Signals',
    remove: 'Remove',
    institutional_integrity: 'Institutional Integrity',
    bar: 'Bar',
    dholera_platform: 'Dholera Platform',
    hectares_monitored: 'Hectares Monitored',
    verified_data: 'Verified Data',
    about_dholera_platform: 'About Dholera Platform',
    verified_maps: 'Verified Dholera Smart City Maps',
    realtime_updates: 'Real-time Infrastructure Updates',
    fee_calculator: 'Development Permission Fee Calculator',
    compliance_verification: 'Land Investment Compliance Verification',
    platform: 'Platform',
    clearance_engine: 'Clearance Engine',
    growth_updates: 'Growth Updates',
    my_vault: 'My Vault',
    legal: 'Legal',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
    contact: 'Contact',
    airport_title: 'Dholera International Airport',
    airport_subtitle: 'The gateway to India’s first smart city.',
    infra_title: 'Smart Infrastructure',
    infra_subtitle: 'World-class industrial ecosystem.',
    tp_maps_title: 'Official TP Maps',
    featured_insights: 'Dholera Investment Insights',
    featured_insights_desc: 'Read verified updates and real estate trends for Dholera Smart City.',
    photo_gallery: 'Dholera Photo Gallery',
    photo_gallery_desc: 'Visual proof of development: Expressway progress, airport construction, and GIS maps.',
    satyaja_plots: 'Satyaja Bliss Grandeur 1 & 2',
    satyaja_tagline: 'Prime Investment Opportunity in Dholera SIR',
    satyaja_desc: 'Investing in Dholera Smart City is a smart decision for the future. Satyaja\'s projects like Bliss 107, Bliss Grandeur, Bliss Rung, and Prelude Industrial Park offer secure, high-yield investment options. Property values are poised for high appreciation due to rapid infrastructural developments. Secure your land assets now.',
    breeze_tagline: 'Planned Plotted Community in Prime Sector',
    breeze_desc: 'A beautifully designed residential plotted development near Dholera\'s central planning zone, offering modular plots ready for construction with asphalt roads, parks, and fast expressway access.',
    aerocity_tagline: 'Commercial & Logistics Plots Near International Airport',
    aerocity_desc: 'Premium commercial and mixed-use plots positioned right near the Dholera International Airport boundary, ideal for premium hotels, service apartments, corporate offices, and logistical services.',
    imperial_tagline: 'Heavy Industrial & Manufacturing Land Blocks',
    imperial_desc: 'High-yield industrial land parcels in TP4B2 designed for heavy machinery setups, storage hubs, assembly facilities, and logistics centers with load-bearing arterial roads and dedicated power grid feeds.',
    book_plot_today: 'Inquire About Satyaja Plots',
    whatsapp_inquiry: 'Discuss on WhatsApp',
    read_more: 'Read Analysis',
    subscribe_title: 'Sign up to receive email updates, fresh news and more!',
    subscribe_desc: 'Get verified infrastructure tracking, real estate developments, and regulatory announcements in Dholera SIR.',
    subscribe_btn: 'Subscribe',
    subscribe_complete: 'Complete Subscription',
    subscribe_success_msg: 'Subscription Activated! You have been added to the master updates queue.',
    subscribe_verification_req: 'Verification Required: Please enter your name and phone number to verify your subscription.',
    established_giants: 'Established Industrial Giants in Dholera SIR',
    established_giants_desc: 'Major global and national conglomerates investing in Dholera’s activation zone and infrastructure development.',
    dream_world_city: 'Dream World City',
    dream_world_tagline: 'Premium Residential Plots & Villas',
    dream_world_desc: 'Located strategically in Dholera SIR, Dream World City offers planned residential plots ranging from 144 to 300 sq.yd., designed for luxury villas and secure long-term capital appreciation.',
    benefits_title: 'Dholera Worldmark Advantages',
    benefits_desc: 'Why investors trust our platform for verified land acquisition and site visitation services.',
    free_visit: 'Complimentary Site Visit & Stay',
    free_visit_desc: 'Pick and drop service from the airport or railway station, complete with a complimentary guest house stay for our outstation clients.',
    strategic_loc: 'High-Growth Strategic Location',
    strategic_loc_desc: 'Positioned in high-yield zones with ready road access, fast expressway connectivity, and close proximity to key industrial nodes.',
  },
  hi: {
    nav_home: 'होम',
    nav_updates: 'ब्लॉग',
    nav_planning: 'योजना',
    nav_investment: 'निवेश',
    nav_contact: 'संपर्क करें',
    btn_unlock: 'अभी अनलॉक करें',
    btn_view: 'नક્શો देखें',
    btn_get_touch: 'संपर्क में रहें',
    search_placeholder: 'दस्तावेज़ खोजें...',
    footer_tagline: 'धोलेरा स्मार्ट सिटी इंफ्रास्ट्रक्चर, निवेश और योजना इंटेलिजेंस के लिए स्वतंत्र पोर्टल।',
    footer_quick_links: 'त्वरित लिंक',
    footer_contact_info: 'संपर्क जानकारी',
    footer_owner: 'मालिक का विवरण',
    footer_address: 'पता',
    footer_email: 'ईमेल',
    footer_phone: 'फोन',
    pdf_cat_official: 'सत्यापित पीडीएफ',
    pdf_cat_naksha: 'नક્શા मैप्स',
    pdf_cat_dp: 'डीपी मैप्स',
    hero_title: 'धोलेरा ग्रोथ प्लेटफॉर्म',
    hero_subtitle: 'स्मार्ट निवेशकों के लिए साक्ष्य-आधारित बुनियादी ढांचा ट्रैकिंग।',
    terms_and_conditions: 'नियम और शर्तें',
    last_updated: 'अंतिम अद्यतन: 20 मई, 2026',
    support_email: 'support@dholeraplatform.com',
    evidence: 'प्रमाण',
    certainty: 'निश्चितता',
    scanning_archives: 'पुरालेख स्कैन कर रहा है...',
    the_loop: 'द लूप',
    proof: 'सबूत',
    step: 'कदम ',
    evidence_signals: 'प्रमाण संकेत',
    remove: 'हटाएं',
    institutional_integrity: 'संस्थागत अखंडता',
    bar: 'बार',
    dholera_platform: 'धोलेरा प्लेटफॉर्म',
    hectares_monitored: 'हेक्टेयर निगरानी',
    verified_data: 'सत्यापित डेटा',
    about_dholera_platform: 'धोलेरा प्लेटफॉर्म के बारे में',
    verified_maps: 'सत्यापित धोलेरा स्मार्ट सिटी मैप्स',
    realtime_updates: 'रीयल-टाइम इन्फ्रास्ट्रक्चर अपडेट',
    fee_calculator: 'विकास अनुमति शुल्क कैलकुलेटर',
    compliance_verification: 'भूमि निवेश अनुपालन सत्यापन',
    platform: 'प्लेटफॉर्म',
    clearance_engine: 'क्लीयरेंस इंजन',
    growth_updates: 'विकास अपडेट',
    my_vault: 'माई वॉल्ट',
    legal: 'कानूनी',
    privacy_policy: 'गोपनीयता नीति',
    terms_of_service: 'सेवा की शर्तें',
    contact: 'संपर्क करें',
    airport_title: 'धोलेरा अंतर्राष्ट्रीय हवाई अड्डा',
    airport_subtitle: 'भारत के पहले स्मार्ट शहर का प्रवेश द्वार।',
    infra_title: 'स्मार्ट इन्फ्रास्ट्रक्चर',
    infra_subtitle: 'विश्व स्तरीय औद्योगिक पारिस्थितिकी तंत्र।',
    tp_maps_title: 'आधिकारिक टीपी मैप्स',
    featured_insights: 'धोलेरा निवेश अंतर्दृष्टि',
    featured_insights_desc: 'धोलेरा स्मार्ट सिटी रियल एस्टेट विकास पर सत्यापित अपडेट और रुझान पढ़ें।',
    photo_gallery: 'धोलेरा फोटो गैलरी',
    photo_gallery_desc: 'विकास का प्रत्यक्ष प्रमाण: एक्सप्रेसवे, हवाई अड्डा निर्माण और जीआईएस नक्शे।',
    satyaja_plots: 'सत्यजा ब्लिस ग्रैन्ड्यूर 1 और 2',
    satyaja_tagline: 'धोलेरा एसआईआर में सबसे भरोसेमंद निवेश मौका',
    satyaja_desc: 'धोलेरा स्मार्ट सिटी में निवेश करना भविष्य के लिए एक समझदारी भरा निर्णय है। Satyaja के सभी प्रोजेक्ट्स जैसे Bliss 107, Bliss Grandeur, Bliss Rung और Prelude Industrial Park आपको सुरक्षित और लाभदायक निवेश का अवसर प्रदान करते हैं। यहां तेजी से विकास हो रहा है, जिससे आने वाले समय में प्रॉपर्टी की कीमतों में बड़ा उछाल देखने को मिलेगा। अभी निवेश करने का सही समय है।',
    breeze_tagline: 'प्रमुख क्षेत्र में नियोजित प्लॉटेड समुदाय',
    breeze_desc: 'धोलेरा के केंद्रीय नियोजन क्षेत्र के पास एक खूबसूरती से डिजाइन किया गया आवासीय प्लॉटेड विकास, जो डामर सड़कों, पार्कों और तेजी से एक्सप्रेसवे पहुंच के साथ निर्माण के लिए तैयार मॉड्यूलर प्लॉट प्रदान करता है।',
    aerocity_tagline: 'अंतर्राष्ट्रीय हवाई अड्डे के पास वाणिज्यिक और रसद भूखंड',
    aerocity_desc: 'धोलेरा अंतर्राष्ट्रीय हवाई अड्डे की सीमा के ठीक पास स्थित प्रीमियम वाणिज्यिक और मिश्रित उपयोग वाले भूखंड, प्रीमियम होटल, सर्विस अपार्टमेंट, कॉर्पोरेट कार्यालयों और रसद सेवाओं के लिए आदर्श।',
    imperial_tagline: 'भारी औद्योगिक और विनिर्माण भूमि ब्लॉक',
    imperial_desc: 'टीपी4बी2 में उच्च उपज वाले औद्योगिक भूमि पार्सल जो भारी मशीनरी सेटअप, स्टोरेज हब, असेंबली सुविधाओं और लॉजिस्टिक्स केंद्रों के लिए लोड-बेयरिंग सड़कों और समर्पित पावर ग्रिड फीड के साथ डिज़ाइन किए गए हैं।',
    book_plot_today: 'सत्यजा प्लॉट्स के बारे में पूछताछ करें',
    whatsapp_inquiry: 'व्हाट्सएप पर चर्चा करें',
    read_more: 'विश्लेषण पढ़ें',
    subscribe_title: 'ईमेल अपडेट, ताजा समाचार और बहुत कुछ प्राप्त करने के लिए साइन अप करें!',
    subscribe_desc: 'धोलेरा एसआईआर में सत्यापित बुनियादी ढांचा ट्रैकिंग, रियल एस्टेट विकास और विनियामक घोषणाओं के साथ अपडेट रहें।',
    subscribe_btn: 'सदस्यता लें',
    subscribe_complete: 'सदस्यता पूरी करें',
    subscribe_success_msg: 'सदस्यता सक्रिय हो गई! आपको मास्टर अपडेट सूची में जोड़ दिया गया है।',
    subscribe_verification_req: 'सत्यापन आवश्यक: सदस्यता पूरी करने के लिए कृपया अपना नाम और फोन नंबर दर्ज करें।',
    established_giants: 'धोलेरा एसआईआर में स्थापित औद्योगिक दिग्गज',
    established_giants_desc: 'धोलेरा के एक्टिवेशन जोन और बुनियादी ढांचा विकास में निवेश करने वाले प्रमुख वैश्विक और राष्ट्रीय समूह।',
    dream_world_city: 'ड्रीम वर्ल्ड सिटी',
    dream_world_tagline: 'प्रीमियम आवासीय प्लॉट और विला',
    dream_world_desc: 'धोलेरा एसआईआर में रणनीतिक रूप से स्थित, ड्रीम वर्ल्ड सिटी 144 से 300 वर्ग गज के नियोजित आवासीय प्लॉट प्रदान करता है, जो लक्जरी विला और सुरक्षित दीर्घकालिक पूंजी वृद्धि के लिए डिज़ाइन किए गए हैं।',
    benefits_title: 'धोलेरा वर्ल्डमार्क के फायदे',
    benefits_desc: 'सत्यापित भूमि अधिग्रहण और साइट विजिट सेवाओं के लिए निवेशक हमारे प्लेटफॉर्म पर क्यों भरोसा करते हैं।',
    free_visit: 'मुफ्त साइट विजिट और ठहरना',
    free_visit_desc: 'हवाई अड्डे या रेलवे स्टेशन से पिक एंड ड्रॉप सेवा, हमारे बाहरी ग्राहकों के लिए मानार्थ गेस्ट हाउस में ठहरने की सुविधा के साथ।',
    strategic_loc: 'उच्च विकास रणनीतिक स्थान',
    strategic_loc_desc: 'सड़क पहुंच, तेज एक्सप्रेसवे कनेक्टिविटी और प्रमुख औद्योगिक नोड्स के निकट उच्च उपज वाले क्षेत्रों में स्थित।',
  },
  gu: {
    nav_home: 'હોમ',
    nav_updates: 'બ્લોગ્સ',
    nav_planning: 'પ્લાનિંગ',
    nav_investment: 'રોકાણ',
    nav_contact: 'સંપર્ક કરો',
    btn_unlock: 'હમણાં અનલોક કરો',
    btn_view: 'નકશો જુઓ',
    btn_get_touch: 'સંપર્કમોં રહો',
    search_placeholder: 'દસ્તાવેજો શોધો...',
    footer_tagline: 'ધોલેરા સ્માર્ટ સિટી ઇન્ફ્રાસ્ટ્રક્ચર, રોકાણ અને પ્લાનિંગ ઇન્ટેલિજન્સ માટેનું સ્વતંત્ર પોર્ટલ.',
    footer_quick_links: 'ક્વિક લિંક્સ',
    footer_contact_info: 'સંપર્ક માહિતી',
    footer_owner: 'માલિકની વિગતો',
    footer_address: 'સરનામું',
    footer_email: 'ઇમેઇલ',
    footer_phone: 'ફોન',
    pdf_cat_official: 'પ્રમાણિત પીડીએફ',
    pdf_cat_naksha: 'નકશા મેપ્સ',
    pdf_cat_dp: 'ડીપી મેપ્સ',
    hero_title: 'ધોલેરા ગ્રોથ પ્લેટફોર્મ',
    hero_subtitle: 'સ્માર્ટ રોકાણકારો માટે પુરાવા-આધારિત ઇન્ફ્રાસ્ટ્રક્ચર ટ્રેકિંગ.',
    terms_and_conditions: 'નિયમો અને શરતો',
    last_updated: 'છેલ્લે અપડેટ કર્યું: 20 મે, 2026',
    support_email: 'support@dholeraplatform.com',
    evidence: 'પુરાવા',
    certainty: 'નિશ્ચિતતા',
    scanning_archives: 'આર્કાઇવ્સ સ્કેન કરી રહ્યું છે...',
    the_loop: 'ધ લૂપ',
    proof: 'સાબિતી',
    step: 'પગલું ',
    evidence_signals: 'પુરાવા સંકેતો',
    remove: 'દૂર કરો',
    institutional_integrity: 'સંસ્થાકીય અખંડિતતા',
    bar: 'બાર',
    dholera_platform: 'ધોલેરા પ્લેટફોર્મ',
    hectares_monitored: 'હેક્ટર મોનિટર કરેલ',
    verified_data: 'પ્રમાણિત ડેટા',
    about_dholera_platform: 'ધોલેરા પ્લેટફોર્મ વિશે',
    verified_maps: 'પ્રમાણિત ધોલેરા સ્માર્ટ સિટી નકશા',
    realtime_updates: 'રીઅલ-ટાઇમ ઇન્ફ્રાસ્ટ્રક્ચર અપડેટ્સ',
    fee_calculator: 'વિકાસ પરવાનગી ફી કેલ્ક્યુલેટર',
    compliance_verification: 'જમીન રોકાણ અનુપાલન ચકાસણી',
    platform: 'પ્લેટફોર્મ',
    clearance_engine: 'ક્લિયરન્સ એન્જિન',
    growth_updates: 'વિકાસ અપડેટ્સ',
    my_vault: 'માય વૉલ્ટ',
    legal: 'કાનૂની',
    privacy_policy: 'ગોપનીયતા નીતિ',
    terms_of_service: 'સેવાની શરતો',
    contact: 'સંપર્ક કરો',
    airport_title: 'ધોલેરા આંતરરાષ્ટ્રીય એરપોર્ટ',
    airport_subtitle: 'ભારતના પ્રથમ સ્માર્ટ સિટીનું પ્રવેશદ્વાર.',
    infra_title: 'સ્માર્ટ ઈન્ફ્રાસ્ટ્રક્ચર',
    infra_subtitle: 'વિશ્વસ્તરીય ઔદ્યોગિક ઇકોસિસ્ટમ.',
    tp_maps_title: 'સત્તાવાર ટીપી મેપ્સ',
    featured_insights: 'ધોલેરા ઇન્વેસ્ટમેન્ટ ઇનસાઇટ્સ',
    featured_insights_desc: 'ધોલેરા સ્માર્ટ સિટી રિયલ એસ્ટેટ ડેવલપમેન્ટ પર પ્રમાણિત અપડેટ્સ અને પ્રવાહો વાંચો.',
    photo_gallery: 'ધોલેરા ફોટો ગેલેરી',
    photo_gallery_desc: 'વિકાસના પ્રત્યક્ષ પુરાવા: એક્સપ્રેસવે પ્રોગ્રેસ, એરપોર્ટ કન્સ્ટ્રક્શન અને જીઆઈએસ નકશા.',
    satyaja_plots: 'સત્યજા બ્લિસ ગ્રાન્ડ્યોર 1 અને 2',
    satyaja_tagline: 'ધોલેરા SIR માં સૌથી વિશ્વસનીય રોકાણની તક',
    satyaja_desc: 'ધોલેરા સ્માર્ટ સિટીમાં રોકાણ કરવું એ ભવિષ્ય માટે એક સમજદારીભર્યો નિર્ણય છે. સત્યજાના પ્રોજેક્ટ્સ જેવા કે Bliss 107, Bliss Grandeur, Bliss Rung અને Prelude Industrial Park સુરક્ષિત અને ઊંચા વળતર આપતા રોકાણના વિકલ્પો પ્રદાન કરે છે. ઝડપી ઇન્ફ્રાસ્ટ્રક્ચર વિકાસને કારણે મિલકતના મૂલ્યોમાં મોટો વધારો થવાની સંભાવના છે. આજે જ તમારો પ્લોટ બુક કરો અને તમારું ભવિષ્ય સુરક્ષિત કરો.',
    breeze_tagline: 'પ્રાઇમ સેક્ટરમાં પ્લાન્ડ પ્લોટેડ કોમ્યુનિટી',
    breeze_desc: 'ધોલેરાના સેન્ટ્રલ પ્લાનિંગ ઝોનની નજીક સુંદર રીતે ડિઝાઇન કરાયેલ રેસિડેન્શિયલ પ્લોટેડ ડેવલપમેન્ટ, જેમાં ડામર રોડ, ગાર્ડન અને ફાસ્ટ એક્સપ્રેસવે એક્સેસ સાથે બાંધકામ માટે તૈયાર પ્લોટ્સ ઓફર કરવામાં આવે છે.',
    aerocity_tagline: 'આંતરરાષ્ટ્રીય એરપોર્ટ નજીક કોમર્શિયલ અને લોજિસ્ટિક્સ પ્લોટ્સ',
    aerocity_desc: 'ધોલેરા ઇન્ટરનેશનલ એરપોર્ટની સરહદની નજીક સ્થિત પ્રીમિયમ કોમર્શિયલ પ્લોટ્સ, જે પ્રીમિયમ હોટેલ્સ, સર્વિસ એપાર્ટમેન્ટ્સ, કોર્પોરેટ ઓફિસ અને લોજિસ્ટિક્સ સેવાઓ માટે આદર્શ છે.',
    imperial_tagline: 'હેવી ઔદ્યોગિક અને મેન્યુફેક્ચરિંગ જમીન બ્લોક્સ',
    imperial_desc: 'TP4B2 માં ઊંચા વળતર આપતા ઔદ્યોગિક જમીનના ટુકડા, જે ભારે મશીનરી સેટઅપ, સ્ટોરેજ હબ, એસેમ્બલી ફેસાઇલિટીઝ અને લોજિસ્ટિક્સ સેન્ટર્સ માટે લોડ-બેરિંગ રોડ અને સમર્પિત પાવર ગ્રીડ કનેક્શન સાથે ડિઝાઇન કરવામાં આવ્યા છે.',
    book_plot_today: 'સત્યજા પ્લોટ્સ વિશે પૂછપરછ કરો',
    whatsapp_inquiry: 'વોટ્સએપ પર ચર્ચા કરો',
    read_more: 'વિશ્લેષણ વાંચો',
    subscribe_title: 'ઇમેઇલ અપડેટ્સ, તાજા સમાચાર અને વધુ મેળવવા માટે સાઇન અપ કરો!',
    subscribe_desc: 'ધોલેરા SIR માં પ્રમાણિત ઇન્ફ્રાસ્ટ્રક્ચર ટ્રેકિંગ, રિયલ એસ્ટેટ ડેવલપમેન્ટ અને રેગ્યુલેટરી જાહેરાતો સાથે અપડેટ રહો.',
    subscribe_btn: 'સબ્સ્ક્રાઇબ કરો',
    subscribe_complete: 'સબ્સ્ક્રિપ્શન પૂર્ણ કરો',
    subscribe_success_msg: 'સબ્સ્ક્રિપ્શન સક્રિય થયું! તમને માસ્ટર અપડેટ્સ કતારમાં ઉમેરવામાં આવ્યા છે.',
    subscribe_verification_req: 'વેરિફિકેશન જરૂરી: સબ્સ્ક્રિપ્શન પૂર્ણ કરવા માટે કૃપા કરીને તમારું નામ અને ફોન નંબર દાખલ કરો.',
    established_giants: 'ધોલેરા SIR માં સ્થાપિત ઔદ્યોગિક દિગ્ગજો',
    established_giants_desc: 'ધોલેરાના એક્ટિવેશન ઝોન અને ઇન્ફ્રાસ્ટ્રક્ચર ડેવલપમેન્ટમાં રોકાણ કરતા મુખ્ય વૈશ્વિક અને રાષ્ટ્રીય જૂથો.',
    dream_world_city: 'ડ્રીમ વર્લ્ડ સિટી',
    dream_world_tagline: 'પ્રીમિયમ રેસિડેન્શિયલ પ્લોટ્સ અને વિલા',
    dream_world_desc: 'ધોલેરા SIR માં વ્યૂહાત્મક રીતે સ્થિત, ડ્રીમ વર્લ્ડ સિટી 144 થી 300 વારના આયોજિત રેસિડેન્શિયલ પ્લોટ્સ ઓફર કરે છે, જે લક્ઝરી વિલા અને સુરક્ષિત લાંબા ગાળાના મૂડી વધારા માટે ડિઝાઇન કરવામાં આવ્યા છે.',
    benefits_title: 'ધોલેરા વર્લ્ડમાર્ક ફાયદાઓ',
    benefits_desc: 'શા માટે રોકાણકારો ચકાસાયેલ જમીન સંપાદન અને સાઇટ વિઝિટ સેવાઓ માટે અમારા પ્લેટફોર્મ પર વિશ્વાસ કરે છે.',
    free_visit: 'મફત સાઇટ મુલાકાત અને રોકાણ',
    free_visit_desc: 'એરપોર્ટ અથવા રેલ્વે સ્ટેશનથી પિક એન્ડ ડ્રોપ સર્વિસ, અમારા બહારના ગ્રાહકો માટે ગેસ્ટ હાઉસમાં મફત રોકાણ સાથે.',
    strategic_loc: 'ઉચ્ચ વિકાસ વ્યૂહાત્મક સ્થાન',
    strategic_loc_desc: 'રોડ એક્સેસ, ફાસ્ટ એક્સપ્રેસવે કનેક્ટિવિટી અને મુખ્ય ઔદ્યોગિક નોડ્સની નજીક ઉચ્ચ ઉપજ આપતા ઝોનમાં સ્થિત.',
  },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = safeLocalStorage.getItem('preferred_lang') as Language | null;
    if (savedLang && translations[savedLang]) {
      setLang(savedLang);
    }
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      safeLocalStorage.setItem('preferred_lang', lang);
    }
  }, [lang, mounted]);

  const t = (key: string) => {
    const validLang = (lang === 'en' || lang === 'hi' || lang === 'gu') ? lang : 'en';
    const dict = Object.prototype.hasOwnProperty.call(translations, validLang) ? translations[validLang] : translations['en'];
    return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
